### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by retornam**
- Update workflows: curl latest kubectl
- Use k8s 1.30 client libs
- Upgrade logr and klog
- Improve LookupDNS
- Ignore peer-finder binary

### CODE REVIEW

**Comment by retornam** [comment]
@tamalsaha this is ready for review. Thanks

**Comment by tamalsaha** [comment]
Thank you for your contribution @retornam ! I really appreciate it.

**Comment by tamalsaha** [comment]
https://github.com/kmodules/peer-finder/releases/tag/v1.3.0

**Comment by retornam** [comment]
@tamalsaha  thank you

**Pull request merged**
